plugins {
    id 'fabric-loom' version '1.14.10'
    id 'maven-publish'
}

version = "3.0.1"

group = "com.maza.addon"

repositories {
    mavenCentral()

    maven {
        name = "meteor-maven"
        url = "https://maven.meteordev.org/releases"
    }

    maven {
        name = "meteor-maven-snapshots"
        url = "https://maven.meteordev.org/snapshots"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation "meteordevelopment:meteor-client:${project.meteor_version}"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}
